---
title: "Setting up a pipeline from scratch: a tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{f-running-pipelines-in-ci}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This vignette demonstrates how to build a `{rixpress}` pipeline that only uses R
derivations. For multilingual pipelines, read the next vignette
`vignette("d-polyglot")`.

# Installing the required software

If you're using `{rixpress}`, you're likely already familiar with its sister
packages `{rix}`, which helps you set up reproducible development environments
for R or Python using Nix. As such you likely already have Nix installed on your
system. If that is not the case, read the following [`{rix}` vignette to learn
how to set up Nix on Linux or
Windows](https://docs.ropensci.org/rix/articles/b1-setting-up-and-using-rix-on-linux-and-windows.html),
or [this one if you're on macOS](https://docs.ropensci.org/rix/articles/b2-setting-up-and-using-rix-on-macos.html).

Once Nix is installed (as well as cachix, and the `rstats-on-nix` cache
configured), you're ready to go.

# Bootstrapping a project

In this vignette I'm going to assume the following:

- you're already familiar with Nix thanks to `{rix}`;
- you only use Nix to manage R environments for data science projects (in other
  words, you don't have a system-installed R);
- you have Nix installed on your system as well as cachix and configured the
  `rstats-on-nix` cache;
- you've read through the previous two vignettes.

If you're already familiar with `{rix}`, you'll likely know that you can use the
following command to get access to a temporary Nix shell that provides R,
`{rix}` and `{rixpress}` (copy and paste it in a terminal in the folder where
you want to start your project):

```
nix-shell --expr "$(curl -sl https://raw.githubusercontent.com/ropensci/rix/main/inst/extdata/default.nix)"
```

This will drop you in a Nix session. Type `R` to start an R session, and type:

```{r, eval = FALSE}
library(rixpress)

rxp_init()
```

This will write two files on the root of your project, `gen-env.R` and
`gen-pipeline.R`. `gen-env.R` will look like this:

```

```

the examples located in the [rixpress_demos
repository](https://github.com/b-rodrigues/rixpress_demos). These examples
demonstrate additional features of `{rixpress}`, including:

- Building Quarto documents
- Creating polyglot pipelines that transfer data between R and Python
- Importing multiple files at once
- Using multiple environments instead of a single `default.nix` file

For a more detailed walkthrough, check out our [video tutorial](video link to
follow).

In the next vignette,, we'll explore how to create
pipelines that combine R and Python code.
